// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe_yl5_li-et6_uRuw_rBgnU0MvI1FBr8',
    appId: '1:748880713592:web:145ab02242e4e6df955a8d',
    messagingSenderId: '748880713592',
    projectId: 'afaq-d4f1c',
    authDomain: 'afaq-d4f1c.firebaseapp.com',
    storageBucket: 'afaq-d4f1c.appspot.com',
    measurementId: 'G-190P2ZC1J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMG-xABm0T9Mfo6CMu6SY-wfFHX2nbQtM',
    appId: '1:748880713592:android:9ddcd39aa391ec58955a8d',
    messagingSenderId: '748880713592',
    projectId: 'afaq-d4f1c',
    storageBucket: 'afaq-d4f1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC18pvB5OTcRa8BeuUuJCFnX7OgPkoVO28',
    appId: '1:748880713592:ios:02510ded2591779f955a8d',
    messagingSenderId: '748880713592',
    projectId: 'afaq-d4f1c',
    storageBucket: 'afaq-d4f1c.appspot.com',
    iosBundleId: 'com.example.afaq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC18pvB5OTcRa8BeuUuJCFnX7OgPkoVO28',
    appId: '1:748880713592:ios:02510ded2591779f955a8d',
    messagingSenderId: '748880713592',
    projectId: 'afaq-d4f1c',
    storageBucket: 'afaq-d4f1c.appspot.com',
    iosBundleId: 'com.example.afaq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe_yl5_li-et6_uRuw_rBgnU0MvI1FBr8',
    appId: '1:748880713592:web:1bef8bd4ed42f521955a8d',
    messagingSenderId: '748880713592',
    projectId: 'afaq-d4f1c',
    authDomain: 'afaq-d4f1c.firebaseapp.com',
    storageBucket: 'afaq-d4f1c.appspot.com',
    measurementId: 'G-4NHQQ2YSH2',
  );
}
